kind: pipeline
type: docker
name: amd64_build

platform:
  os: linux
  arch: amd64

steps:
- name: docker_build_version
  image: plugins/docker
  when:
    event:
      - push
    branch:
      - master
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: naorlivne/webhook_auth_poc
    tags:
      - linux-amd64
      - linux-amd64-v${DRONE_BUILD_NUMBER}

image_pull_secrets:
- dockerconfig

---
kind: pipeline
type: docker
name: arm64_build

platform:
  os: linux
  arch: arm64

steps:
- name: docker_build_version
  image: plugins/docker
  when:
    event:
      - push
    branch:
      - master
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: naorlivne/webhook_auth_poc
    tags:
      - linux-arm64
      - linux-arm64-v${DRONE_BUILD_NUMBER}

image_pull_secrets:
- dockerconfig

---
kind: pipeline
type: docker
name: publish_docker_manifest

trigger:
  event:
  - push
  branch:
  - master

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target:  naorlivne/webhook_auth_poc
    template: naorlivne/webhook_auth_poc:OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

depends_on:
- amd64_build
- arm64_build

---
kind: pipeline
type: docker
name: publish_docker_manifest_build_number

trigger:
  event:
  - push
  branch:
  - master

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target:  naorlivne/webhook_auth_poc:v${DRONE_BUILD_NUMBER}
    template: naorlivne/webhook_auth_poc:OS-ARCH-v${DRONE_BUILD_NUMBER}
    platforms:
      - linux/amd64
      - linux/arm64

depends_on:
- amd64_build
- arm64_build

---
kind: pipeline
type: docker
name: publish_changelog

trigger:
  event:
  - push
  branch:
  - master

steps:
- name: create_changelog
  image: naorlivne/drone-github-changelog-generator
  settings:
    github_user: ${DRONE_REPO_NAMESPACE}
    github_project: ${DRONE_REPO_NAME}
    output_path: CHANGELOG.md
  environment:
    CHANGELOG_GITHUB_TOKEN:
      from_secret: changelog_github_token

depends_on:
- amd64_build
- arm64_build

---
kind: pipeline
type: docker
name: notify

steps:
- name: notify
  image: drillster/drone-email
  settings:
    host: aspmx.l.google.com
    port: 25
    from: dronealert@dronealert.com
    recipients: [ naorlivne@gmail.com ]
    recipients_only: true

trigger:
  status:
  - failure

depends_on:
- publish_docker_manifest
- publish_docker_manifest_build_number
- publish_changelog
