version: '3'

services:
   redis:
     container_name: redis
     hostname: redis
     image: redis:4-alpine3.9
     ports:
       - "6379:6379"
     restart: unless-stopped


# TODO - create "alice" requester API container

# TODO - create "bob" receiver API container

# TODO - create "eve" attacker API container